import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  ArrowCounterClockwise, ShareNetwork, DownloadSimple,
  Speedometer, Info, TrendUp, Sparkle, ShieldCheck,
  GasPump, Cpu, Medal, Wallet, ChartLineUp, CarProfile 
} from '@phosphor-icons/react';
import confetti from 'canvas-confetti';
import { FEATURE_IMPORTANCE, formatINR } from '../data/carData';
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar 
} from 'recharts';

export default function PredictionResult({
  formData,
  valuationResult,
  onReset
}) {
  const [animatedPrice, setAnimatedPrice] = useState(0);
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState('overview');

  const targetPrice = valuationResult?.price || 845000;

  useEffect(() => {
    try {
      confetti({
        particleCount: 50,
        spread: 60,
        origin: { y: 0.6 },
        colors: ['#38bdf8', '#2563eb', '#60a5fa', '#93c5fd']
      });
    } catch (e) {}

    const duration = 1200;
    const startTime = performance.now();

    const updateCounter = (currentTime) => {
      const elapsed = currentTime - startTime;
      const progress = Math.min(elapsed / duration, 1);
      const ease = progress === 1 ? 1 : 1 - Math.pow(2, -10 * progress);
      const currentVal = Math.round(ease * targetPrice);
      setAnimatedPrice(currentVal);

      if (progress < 1) {
        requestAnimationFrame(updateCounter);
      }
    };

    requestAnimationFrame(updateCounter);
  }, [targetPrice]);

  const handleShare = () => {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(
        `AutoPredict Valuation: ${formData.brand} ${formData.model} (${formData.year}) estimated at ${formatINR(targetPrice)}`
      );
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  const handlePrint = () => {
    // A trick to ensure all animations are finished before print
    setTimeout(() => {
      window.print();
    }, 100);
  };

  const currentYear = new Date().getFullYear();
  const depreciationData = Array.from({ length: 6 }).map((_, i) => {
    const val = targetPrice * Math.pow(0.88, i);
    return { year: currentYear + i, value: Math.round(val) };
  });

  const comps = [
    { id: 1, title: `${formData.year} ${formData.brand} ${formData.model}`, tag: 'Great Deal', price: targetPrice * 0.98, distance: '12 km away' },
    { id: 2, title: `${formData.year} ${formData.brand} ${formData.model}`, tag: 'Fair Price', price: targetPrice * 1.05, distance: '5 km away' },
    { id: 3, title: `${formData.year} ${formData.brand} ${formData.model}`, tag: 'Premium Spec', price: targetPrice * 1.12, distance: '22 km away' }
  ];

  const radarData = [
    { subject: 'Brand Equity', score: 85 },
    { subject: 'Condition', score: formData.condition === 'New' || formData.condition === 'Like New' ? 95 : 70 },
    { subject: 'Mileage', score: formData.mileage < 30000 ? 90 : 60 },
    { subject: 'Market Demand', score: 88 },
    { subject: 'Age (Recency)', score: formData.year >= currentYear - 3 ? 90 : 65 }
  ];

  const fuelCost = Math.round(targetPrice * 0.15);
  const insuranceCost = Math.round(targetPrice * 0.08);
  const maintenanceCost = Math.round(targetPrice * 0.12);
  const totalCost = fuelCost + insuranceCost + maintenanceCost;

  return (
    <div className="w-full bg-white rounded-[2rem] print:rounded-none print:shadow-none print:p-0 print:m-0 print:w-full print:max-w-none">
      
      <style type="text/css">
        {`
          @media print {
            @page { size: A4 portrait; margin: 15mm; }
            body { -webkit-print-color-adjust: exact; print-color-adjust: exact; background: white !important; }
            /* Hide the root app backgrounds and margins */
            #root { padding: 0 !important; margin: 0 !important; }
            section { padding: 0 !important; margin: 0 !important; }
          }
        `}
      </style>

      {/* Print-only Certificate Header */}
      <div className="hidden print:block text-center border-b-2 border-slate-900 pb-4 mb-6 mt-0">
        <h1 className="text-3xl font-black text-slate-900 tracking-tight uppercase">Official Certificate of Valuation</h1>
        <p className="text-slate-600 mt-1 font-mono text-sm">Generated by AutoPredict AI Engine • {new Date().toLocaleDateString()}</p>
      </div>

      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center justify-between flex-wrap gap-4 mb-6 pb-4 border-b border-slate-200 print:hidden p-8 pb-0"
      >
        <div className="flex items-center gap-2.5">
          <span className="flex h-2.5 w-2.5 rounded-full bg-emerald-500 animate-pulse" />
          <span className="text-xs uppercase tracking-wider font-bold text-slate-500">Valuation Complete • Model V4.2 Inference</span>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={handleShare}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white hover:bg-slate-50 border border-slate-200 text-xs font-semibold text-slate-600 transition-colors shadow-sm"
          >
            <ShareNetwork weight="bold" className="w-3.5 h-3.5" />
            <span>{copied ? 'Copied Link!' : 'Share Estimate'}</span>
          </button>
          <button
            onClick={handlePrint}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white hover:bg-slate-50 border border-slate-200 text-xs font-semibold text-slate-600 transition-colors shadow-sm"
          >
            <DownloadSimple weight="bold" className="w-3.5 h-3.5" />
            <span>Export Certificate</span>
          </button>
        </div>
      </motion.div>

      <div className="flex overflow-x-auto gap-2 mb-6 pb-2 hide-scrollbar print:hidden px-8">
        {[
          { id: 'overview', label: 'Overview', icon: Speedometer },
          { id: 'market', label: 'Market Insights', icon: TrendUp },
          { id: 'ai', label: 'AI Breakdown', icon: Cpu },
          { id: 'cost', label: 'Cost to Own', icon: Wallet }
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-bold transition-all whitespace-nowrap ${
              activeTab === tab.id
                ? 'bg-blue-600 text-white shadow-md shadow-blue-500/20'
                : 'bg-white text-slate-500 border border-slate-200 hover:bg-slate-50'
            }`}
          >
            <tab.icon weight={activeTab === tab.id ? 'fill' : 'bold'} className="w-4 h-4" />
            {tab.label}
          </button>
        ))}
      </div>

      {/* Main Content Area - Print respects this by displaying all important blocks */}
      <div className="px-8 pb-8 print:p-0">
        
        {/* Overview Block - Always visible on print */}
        <div className={`grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch print:flex print:flex-col print:gap-4 ${activeTab !== 'overview' && 'hidden print:flex'}`}>
          
          <div className="lg:col-span-7 flex flex-col justify-between p-8 sm:p-10 rounded-3xl bg-gradient-to-b from-blue-50 via-white to-slate-50 border border-blue-100 shadow-md relative overflow-hidden print:shadow-none print:border print:border-slate-300 print:rounded-xl print:p-6 print:bg-white print:break-inside-avoid">
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-80 h-80 bg-blue-400/20 rounded-full blur-3xl pointer-events-none print:hidden" />
            <div className="relative z-10 text-center sm:text-left print:text-center">
              <span className="text-xs font-bold uppercase tracking-widest text-blue-600 mb-1 block">AutoPredict Valuation Engine</span>
              <h3 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight print:text-2xl">Estimated Market Value</h3>
            </div>

            <div className="relative z-10 my-8 py-6 flex flex-col items-center justify-center print:my-4 print:py-2">
              <div className="relative w-72 h-44 sm:w-88 sm:h-52 flex items-center justify-center print:w-64 print:h-40 print:scale-90">
                <svg className="w-full h-full overflow-visible" viewBox="0 0 240 140">
                  <defs>
                    <linearGradient id="arcGradientLight" x1="0%" y1="0%" x2="100%" y2="0%">
                      <stop offset="0%" stopColor="#2563eb" />
                      <stop offset="50%" stopColor="#3b82f6" />
                      <stop offset="100%" stopColor="#0ea5e9" />
                    </linearGradient>
                    <filter id="glowLight" x="-20%" y="-20%" width="140%" height="140%">
                      <feGaussianBlur stdDeviation="3" result="blur" />
                      <feComposite in="SourceGraphic" in2="blur" operator="over" />
                    </filter>
                  </defs>
                  <path d="M 25 125 A 95 95 0 0 1 215 125" fill="none" stroke="rgba(0,0,0,0.06)" strokeWidth="12" strokeLinecap="round" />
                  <path d="M 25 125 A 95 95 0 0 1 215 125" fill="none" stroke="url(#arcGradientLight)" strokeWidth="12" strokeLinecap="round" strokeDasharray="300" strokeDashoffset="45" filter="url(#glowLight)" className="transition-all duration-1000 ease-out print:filter-none print:stroke-blue-600" />
                  {[0, 25, 50, 75, 100].map((tick, i) => {
                    const angle = Math.PI - i * Math.PI / 4;
                    const x1 = 120 + 82 * Math.cos(angle);
                    const y1 = 125 - 82 * Math.sin(angle);
                    const x2 = 120 + 72 * Math.cos(angle);
                    const y2 = 125 - 72 * Math.sin(angle);
                    return <line key={i} x1={x1} y1={y1} x2={x2} y2={y2} stroke="rgba(0,0,0,0.15)" strokeWidth="2" />;
                  })}
                </svg>
                <div className="absolute inset-x-0 bottom-6 flex flex-col items-center justify-center text-center px-4 print:bottom-4">
                  <span className="text-3xl sm:text-4xl font-bold tracking-tighter text-slate-900 font-mono print:text-3xl">
                    {formatINR(targetPrice)}
                  </span>
                  <span className="mt-1.5 text-xs sm:text-sm font-bold text-blue-600 tracking-wide uppercase print:text-xs">AI Estimated Price</span>
                </div>
              </div>
              <div className="mt-4 flex items-center justify-center gap-3 px-5 py-2 rounded-full bg-white border border-slate-200 text-xs sm:text-sm text-slate-600 shadow-sm print:shadow-none print:border-slate-300 print:mt-0">
                <span className="text-slate-500 font-medium">Market Range:</span>
                <span className="font-bold text-slate-800 font-mono">{formatINR(valuationResult?.lowerRange || Math.round(targetPrice * 0.95))}</span>
                <span className="text-slate-400">—</span>
                <span className="font-bold text-slate-800 font-mono">{formatINR(valuationResult?.upperRange || Math.round(targetPrice * 1.05))}</span>
              </div>
            </div>

            <div className="relative z-10 pt-6 border-t border-slate-200/60 flex flex-col sm:flex-row items-center justify-between gap-4 print:pt-4 print:border-slate-200">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-blue-100 border border-blue-200 flex items-center justify-center shrink-0 print:border-slate-300 print:bg-white">
                  <ShieldCheck weight="fill" className="w-5 h-5 text-blue-600" />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-bold text-slate-800">Prediction Reliability</span>
                    <span className="px-2 py-0.5 rounded-full text-[11px] font-bold bg-blue-100 text-blue-700 border border-blue-200 print:border-slate-300 print:bg-white">High Reliability</span>
                  </div>
                  <p className="text-xs text-slate-500 mt-0.5 font-medium">Based on 460+ recent market comps for similar specs</p>
                </div>
              </div>
            </div>
          </div>

          <div className="lg:col-span-5 flex flex-col justify-between p-6 sm:p-8 rounded-3xl bg-white border border-slate-200 shadow-md relative print:shadow-none print:border print:border-slate-300 print:rounded-xl print:p-6 print:break-inside-avoid">
            <div className="mt-5 print:mt-0">
              <div className="flex items-baseline justify-between">
                <h4 className="text-2xl font-bold text-slate-900 tracking-tight print:text-xl">
                  {formData.brand || 'BMW'} {formData.model || 'X5'}
                </h4>
                <span className="text-xs font-mono font-bold px-2 py-0.5 rounded bg-blue-100 text-blue-700 border border-blue-200 print:border-slate-300 print:bg-white">Verified Spec</span>
              </div>
            </div>

            <div className="mt-6 grid grid-cols-2 gap-3 print:mt-4 print:gap-2">
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 print:border-slate-300 print:bg-white">
                <span className="text-[11px] font-bold text-slate-500 block mb-0.5">Mileage</span>
                <span className="text-sm font-semibold text-slate-800">{Number(formData.mileage || 45000).toLocaleString('en-IN')} km</span>
              </div>
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 print:border-slate-300 print:bg-white">
                <span className="text-[11px] font-bold text-slate-500 block mb-0.5">Engine</span>
                <span className="text-sm font-semibold text-slate-800">{formData.engineSize || '3.0'} L</span>
              </div>
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 print:border-slate-300 print:bg-white">
                <span className="text-[11px] font-bold text-slate-500 block mb-0.5">Fuel</span>
                <span className="text-sm font-semibold text-slate-800">{formData.fuelType || 'Petrol'}</span>
              </div>
              <div className="p-3 rounded-xl bg-slate-50 border border-slate-200 print:border-slate-300 print:bg-white">
                <span className="text-[11px] font-bold text-slate-500 block mb-0.5">Transmission</span>
                <span className="text-sm font-semibold text-slate-800">{formData.transmission || 'Automatic'}</span>
              </div>
              <div className="col-span-2 p-3 rounded-xl bg-slate-50 border border-slate-200 flex items-center justify-between print:border-slate-300 print:bg-white">
                <div>
                  <span className="text-[11px] font-bold text-slate-500 block mb-0.5">Condition</span>
                  <span className="text-sm font-semibold text-emerald-600 flex items-center gap-1.5">
                    <Medal weight="fill" className="w-4 h-4" />
                    {formData.condition || 'Like New'}
                  </span>
                </div>
                <span className="text-[10px] font-bold text-slate-600 bg-slate-200 px-2 py-1 rounded print:border print:border-slate-300 print:bg-white">Grade A Tier</span>
              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-slate-200 print:hidden">
              <button
                onClick={onReset}
                className="w-full flex items-center justify-center gap-2 py-3 px-4 rounded-xl bg-white hover:bg-slate-50 border border-slate-200 text-sm font-bold text-slate-600 hover:text-slate-900 transition-all shadow-sm"
              >
                <ArrowCounterClockwise weight="bold" className="w-4 h-4 text-blue-500" />
                <span>Modify Inputs & Recalculate</span>
              </button>
            </div>
          </div>
        </div>

        {/* AI Breakdown Block - Shows on print or if activeTab === 'ai' */}
        <div className={`mt-8 p-8 sm:p-10 rounded-3xl bg-white border border-slate-200 shadow-md flex flex-col md:flex-row gap-10 items-center print:mt-4 print:p-6 print:border print:border-slate-300 print:rounded-xl print:shadow-none print:break-inside-avoid ${activeTab !== 'ai' && 'hidden print:flex'}`}>
          <div className="flex-1 w-full">
            <div className="mb-6 print:mb-4">
              <h4 className="text-2xl font-bold text-slate-900 flex items-center gap-2 mb-2 print:text-xl">
                <Cpu className="w-6 h-6 text-indigo-600" /> Neural Network Insight
              </h4>
              <p className="text-slate-500 leading-relaxed print:text-sm">Our AI evaluates hundreds of parameters. Here is a breakdown of the key factors influencing your vehicle's specific valuation today.</p>
            </div>
            <div className="space-y-5 mt-8 print:mt-4 print:space-y-3">
              {FEATURE_IMPORTANCE.map((item, index) => (
                <div key={item.name} className="space-y-1.5">
                  <div className="flex items-center justify-between text-sm">
                    <span className="font-bold text-slate-700">{item.name}</span>
                    <span className="font-mono font-bold text-indigo-600">{item.percentage}%</span>
                  </div>
                  <div className="h-3 w-full rounded-full bg-slate-100 border border-slate-200 overflow-hidden p-0.5 print:border-slate-300 print:bg-white print:h-2">
                    <div style={{ width: `${item.percentage * 5}%` }} className={`h-full rounded-full bg-gradient-to-r ${item.color} shadow-sm print:bg-slate-400 print:bg-none`} />
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="flex-1 w-full h-[350px] print:h-[220px]">
            <ResponsiveContainer width="100%" height="100%">
              <RadarChart cx="50%" cy="50%" outerRadius="70%" data={radarData}>
                <PolarGrid stroke="#e2e8f0" />
                <PolarAngleAxis dataKey="subject" tick={{ fill: '#64748b', fontSize: 11, fontWeight: 600 }} />
                <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                <Radar name="Vehicle Score" dataKey="score" stroke="#4f46e5" strokeWidth={2} fill="#6366f1" fillOpacity={0.4} />
              </RadarChart>
            </ResponsiveContainer>
          </div>
        </div>
        
        {/* Certificate Footer - Only visible on print */}
        <div className="hidden print:block mt-8 pt-4 border-t-2 border-slate-900">
          <div className="flex justify-between items-center text-sm font-bold text-slate-500">
            <div>
              <p>Certified by AutoPredict AI</p>
              <p className="text-xs">Model Version: V4.2 Inference (ExtraTreesRegressor)</p>
            </div>
            <div>
              <p>Reference ID: AP-{Math.random().toString(36).substring(2, 10).toUpperCase()}</p>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}